### ISSUE TITLE
[RFC] Don't throw when channel closes during Channel::request

### ISSUE THREAD

**Issue by masad-frost** [replit/crosis#18]
Right now when you send a request and the channel closes; whether it is due to client closing or calling `channel.close` we throw an error for that promise. I think it would be cleaner if we just returned something instead.

Which means if you want to handle that instance you need to put `channe.request` in a try catch, catch the error 

This is common in our codebase, it's ugly and tedious!
```ts
let res
try {
  res = channel.request({ ... })
} catch (e) {
  if (/* assert if error is channel closed */) {
    handleChannelClosed();
    return;
  }

  throw e;
}
```
Not sure if this makes sense but I'm thinking this is better than throwing.
```ts
enum ChannelCloseReason {
  ClientClosed, // this means you called `Client::close`
  ClientDisconnect, // this means the websocket died unexpectedly
  ChannelClosed, // this means you called `Channel::close`
}

type RequestResult =
  | api.Command
  | { channelClosed: ChannelCloseReason; closeStatus: null }
  | { channelClosed: ChannelCloseReason.ChannelClosed; closeStatus: api.CloseChannelRes.Status };

interface Channel {
  request(cmd: api.Command): Promise<RequestResult>;
}
```

**Comment by masad-frost** [comment]
So you end up with this
```ts
const res = channel.request({ ... });

if (res.channelClosed) {
  handleChannelClosed();

  return;
}
```

You can also assert the closing reason and react accordingly.

**Comment by jeremypress** [comment]
I like this 👍. Is close status relevant in this case? I think we already have everything we need from the close reason.

**Comment by moudy** [comment]
i like it

**Comment by masad-frost** [comment]
Yeah close status is not relevant I guess. 

I went with https://github.com/replit/crosis/pull/19, it's close to this API but a little simpler. Especially because here `RequestResult` doesn't have a discriminate union!
