### ISSUE TITLE
Plugin Crashing the repl.it Console

### ISSUE THREAD

**Issue by sudiptog81** [replit/crosis#36]
Clearing the console with Ctrl+L keybinding twice results in a plugin crash with the following error message, probable front-end bug.

`Error: TypeError: Cannot read property 'copyCellsFrom' of undefined`

![image](https://user-images.githubusercontent.com/11232940/91652545-18d85680-eab6-11ea-9b4e-2b2cee3c9f8b.png)

**Comment by sergeichestakov** [comment]
Hey thanks for opening this issue! Unfortunately, this isn't the best place to flag this as this bug isn't directly related to crosis. I'd recommend opening an issue on our canny (https://replit.canny.io/) instead.
